@startuml 04_Diagrama_Casos_Uso.puml

title Sistema Lavadero - Diagrama de Casos de Uso


left to right direction


actor Cliente
actor Empleado
actor Supervisor
actor Proveedor
actor Administrador


rectangle "Sistema Lavadero" {


usecase "Registrar cliente" as UC1

usecase "Registrar vehículo" as UC2

usecase "Consultar catálogo\nproductos y servicios" as UC3

usecase "Crear orden de venta" as UC4

usecase "Solicitar servicio\nde lavado" as UC5


usecase "Gestionar productos" as UC6

usecase "Gestionar categorías" as UC7

usecase "Gestionar proveedores" as UC8

usecase "Crear cotización\nde compra" as UC9

usecase "Registrar recepción\nde pedido" as UC10


usecase "Asignar cubículo" as UC11

usecase "Aplicar servicio\nal vehículo" as UC12

usecase "Actualizar cola\nde vehículos" as UC13


usecase "Gestionar empleados" as UC14


}


Cliente --> UC1
Cliente --> UC2
Cliente --> UC3
Cliente --> UC4
Cliente --> UC5


Empleado --> UC3
Empleado --> UC4
Empleado --> UC6
Empleado --> UC8
Empleado --> UC9
Empleado --> UC10
Empleado --> UC12


Supervisor --> UC11
Supervisor --> UC13
Supervisor --> UC14


Proveedor --> UC10


Administrador --> UC6
Administrador --> UC7
Administrador --> UC14


@enduml