@startuml   05_Diagrama_Secuencia.puml

title Secuencia - Solicitud de Servicio Lavadero


actor Cliente

participant "Empleado" as Empleado

participant "Sistema" as Sistema

participant "OrdenVenta" as Orden

participant "Vehiculo" as Vehiculo

participant "Servicio" as Servicio

participant "Cubiculo" as Cubiculo



Cliente -> Empleado : Solicita servicio

Empleado -> Sistema : Busca cliente

Sistema -> Sistema : Validar datos


Empleado -> Sistema : Registrar orden venta


Sistema -> Orden : Crear orden


Orden -> Vehiculo : Asociar vehículo


Empleado -> Sistema : Seleccionar servicio


Sistema -> Servicio : Consultar servicio


Sistema -> Cubiculo : Verificar disponibilidad


Cubiculo --> Sistema : Disponible


Sistema -> Cubiculo : Asignar vehículo


Empleado -> Servicio : Aplicar servicio


Servicio --> Cliente : Servicio finalizado


@enduml